services:
  server:
    build:
      context: .
      target: dev
    ports:
      - 3005:3005
      - 9229:9229
    environment:
      NODE_ENV: development
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fantastic
      POSTGRES_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/usr/src/app/src
  db:
    image: postgres
    restart: always
    user: postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=fantastic
      - POSTGRES_PASSWORD=password
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 2s
      timeout: 5s
      retries: 30
volumes:
  db-data:
